defaults:
  - /qd@qd_algorithm: map_elites

_target_: src.task.dnaqd.QDSearchDNA

popsize: 100

scoring_function: ${get_fn:src.evo.qd.qd_score_x_coverage}

problem: ???
qd_algorithm:
  emitter:
    batch_size: ${task.popsize}
