defaults:
  - /qd@qd_algorithm: map_elites

_target_: src.task.dnaqd.QDSearchDNA

popsize: 100

score_aggregator: null  # default aggregates qd_score and coverage

problem: ???
qd_algorithm:
  emitter:
    batch_size: ${task.popsize}
