_target_: src.task.input_search.InputOptimization

datamodule: ???  # to be filled out in concrete experiment
prepare_batch: null
loss_fn: ???  # to be filled out in concrete experiment

input_size: ???

steps: 10
optim:
  _target_: optax.adam
  learning_rate: 1e-4
