_target_: src.evo.qd.MapElitesEs
_partial: True
n_centroids: 100,
n_descriptors: ???,
descriptor_min_val: ???
descriptor_max_val: ???

emitter:
  _target_: qdax.core.emitters.standard_emitters.MixingEmitter
  mutation_fn: None
  variation_fn:
    _target_: qdax.core.emitters.mutation_operators.isoline_variation
    _partial_: True
    iso_sigma: 0.005
    line_sigma: 0.05
  variation_percentage: 1.0
  batch_size: 1  # this is the population size

metrics_function:
  _target_: qdax.utils.metrics.default_qd_metrics
  _partial_: True
  qd_offset: 0  # this is problem dependant. should be set so that qd scores are positive
