# @package _global_

defaults:
  - _self_  # override defaults
  - task: ???
  - model: ???
  - trainer: ???
  - callbacks: default
  - logger: tensorboard
  - paths: default
  - hydra: default

  # Set an experiment with all the above set to specific values
  - experiment: null

  # Hyperparemeter optimization
  - hparams_search: null


task_name: train

tags: ["dev"]

seed: null

ckpt_path: null  # path to resume training

disable_jit: False
